### ISSUE TITLE
Revise Writing a rails migration

### ISSUE THREAD

**Issue by dpickett** [LaunchAcademy/codecabulary#16]

**Comment by DanAlberts** [comment]
Since this is what we mentioned our _ideal_ or most visited doc, I found little to change or update, seeing as everything here is still best practice today. Added links to mentioned docs, which seemed to not have been added although indicated. Fixed a few broken markup formatting that was causing a list to slide (at least in my browser.) And fixed minor spelling/grammar mistakes.

**Comment by dpickett** [comment]
revisions made in #26
